### ISSUE TITLE
Feature Request: keyboard shortcut

### ISSUE THREAD

**Issue by jedahan** [ttyridal/masterpassword-firefox#1]
Would be cool if we could add a keyboard shortcut to autopaste for the detected url in whatever password box is focused

**Comment by ttyridal** [comment]
Indeed that would be great, and it should be doable.

This is imho potentially better than automatically filling out any password field we might find in the active document.

**Comment by ttyridal** [comment]
The feature is in the repo now.. hotkey is ctrl-alt-p by default.. 
a bit of a crude way to change it though.. has to know the firefox key names (and rules)

**Comment by jedahan** [comment]
That's awesome! Thanks so much!
