### ISSUE TITLE
store the id

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#10]
for a login it is necessary to supply a password but also an id.
i get several ids then it is necessary to "store" them and to supply them when logging .

"store" = "any way to found again"

**Comment by ttyridal** [comment]
Do you think a separate field (like the original apps) or extract the id from <userid>@site is best?

With several id's stored on the same site, they'll have the same password if one does not modify the site string anyway.

**Comment by promeneur** [comment]
> > Do you think a separate field (like the original apps) or extract the id from @site is best?

from the point of view of a user the way to store an id is a dev pb not a user pb .

> > With several id's stored on the same site, they'll have the same password if one does not modify the site string anyway.

let's be clear . if i say "i get several ids" i don't mean "i get several ids for one site" . i use only one id per site . for about 100 sites i subscribed i use about 10 ids .

Linux distributions , MS Windows are multi-user OS . if i understand since Android 4.2 for Tablet and since Android Lollipop for smartphone also is multi-user OS . Masterpassword is a multi-user application . Then if each one uses correctly the OS or Masterpassword then the case "several users for one site" does not occurs . No ?

**Comment by ttyridal** [comment]
> > Do you think a separate field (like the original apps) or extract the id from @site is best?
> > from the point of view of a user the way to store an id is a dev pb not a user pb .

Sure, It was a user experience question. Would you prefer a separate input box for the id, or use the site string. (eg alt1 or alt2 as attached)

![alt1](https://cloud.githubusercontent.com/assets/7912255/7957111/43107728-09e5-11e5-8d53-8a04f7c7d84a.jpg)
![alt2](https://cloud.githubusercontent.com/assets/7912255/7957110/430efd6c-09e5-11e5-9f35-c8433aa21b2c.jpg)

> Then if each one uses correctly the OS or Masterpassword then the case "several users for one site" does not occurs . No ?

Of course, the masterpassword sites will be stored pr os- user account

**Comment by promeneur** [comment]
> > Would you prefer a separate input box for the id, or use the site string. (eg alt1 or alt2 as attached) ?

a separate input box for the id .
it's less confusing .
