### ISSUE TITLE
Generating password failed

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#15]
I get the (Failed) message often when generating site passwords. At the bottom it says 'Waiting didn't help :(' 

I will provide more information as I can, just tell me what you need and where to find it.

Windows 10 Pro 64bit
4GB Ram
2.4GHz i3 M370
Firefox 40.0.3

**Comment by ttyridal** [comment]
Hi, Is there any hint in the browser console (menu: tools->web developper->Browser Console (Ctrl-Shift-J)) ? - You can filter on masterpassword in the log window.

Which version is it (of mpw)? From mozilla addon store? beta or release channel?  Has it always been like that? any change with windows 10 ?

**Comment by ghost** [comment]
TypeError: asm.js type error: Disabled by javascript.options.asmjs in about:config scrypt-asm.js

99.8.1-signed from the store. It's been doing it for a while even on windows 8.1 pro 64bit

**Comment by ttyridal** [comment]
Right. Any particular reason for having disabled asmjs ? (it should be shipped _enabled_ by default). 

The short answer is that it won't work without asmjs. The crypto library I'm using is in C, compiled to asmjs.

I assume this is _never_ working on this setup. Or it could be that the asm.js code is then parsed as "regular" javascript, which would probably take a very long time (mpw bails out with the error message you're seeing after ~.5s) I can build a "wait for as long as it takes" test build for you, but I suspect it's not usable.

**Comment by ghost** [comment]
It's not disabled, so I don't know why it says that. It does work, 2 out of three times if i had to guess.

**Comment by ttyridal** [comment]
Right.. I've compiled a test build where the loading mechanism is changed such that scrypt-asm.js should always load first, and synchronously: http://torbjorn.tyridal.no/ymse/mp-ff-v0.99.8.2.xpi

**Comment by ghost** [comment]
It seems to be corrected now.

**Comment by ttyridal** [comment]
That's good. Unfortunately the change didn't make the 1.0 release just
published (there is a multi-weeks delay through the review process), but
the load time penalty is probably neglectable so I'll add it for the future.

Thanks for reporting & testing
