### ISSUE TITLE
Site matching

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#16]
site matching does not work on imported .mpsites file when the username is included, and the username is an email address.

example:
myemail@gmail.com@foo.com --- this will site match to gmail.com and NOT foo.com like expected

This is on the 1.0 release on the mozilla store.

**Comment by ttyridal** [comment]
Confirmed. the site name to "matching" on import is rather limited.
It should be easy enough to correct (work around) in the configuration view.

**Comment by ttyridal** [comment]
Thanks for reporting!

**Comment by ttyridal** [comment]
A fix for this and the loading issues (Issue #15) has been released in the beta channel on mozilla store (https://addons.mozilla.org/en-US/firefox/addon/masterpassword-firefox/versions/beta)
