### ISSUE TITLE
mpw does not use kwallet

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#20]
opensuse 13.1 x86_64
kde 4.14.10
FF 42.0
i selected kwallet in the options of mpw
then
i close and launch FF
then
kwallet asked for me to authorize mpw to use kwallet
then
i answer "always"
then
in kwallet i suppress the id and pwd for a site
then
i go to the site
then
i click on the button "..."
then
in mpw i complete the site name to find again the previously generated pwd and i type the id
i verified that mpw generate the same pwd
then
in the site template i type the id
then
Ctrl_V to copy the pwd from mpw
then
i don't accept that FF records the id and pwd
then
i disconnect from the site
then
i close FF
then
i go to kwallet
then
no mpw folder and no id about the site

i assume mpw keeps on using its own file to store the id . no ? 
i wonder if i must to delete some mpw file or contents

**Comment by ttyridal** [comment]
Hi, 

what are you expecting to happen? 

Mpw stores only one thing in the kwallet - Your master password. All site configuration is stored "inside" Firefox.

> then
> in kwallet i suppress the id and pwd for a site

Could you explain this again ?  Do you have id & password for a site stored in kwallet and expect mpw to retrieve and use that instead of the generated one?

**Comment by promeneur** [comment]
i believed when discovering the option to select kwallet that mpw store all about a site (not the pwd) and can retrieve these data and fill the id and pwd of any site template. thus mpw could replace FF pwd manager .

so now i know that : 
- no more need to fill the master password at each FF session but only at each kde session . thanks for this new feature .
