### ISSUE TITLE
Import Errors

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#21]
I'm not able to import a mpsites file into firefox that was exported from iOS. It says its not a mpsites file. 
I'm using 2.0.0 of this addon. 2.0.0RC2 also has the same issue.

**Comment by ttyridal** [comment]
Hopefully this is fixed in 2.0.1pre2, now available in the beta-channel.

**Comment by ttyridal** [comment]
Hi @linwiz Did you have a chance to see if pre2 fixed this?

**Comment by ghost** [comment]
Sorry, I didn't think to post after you closed the issue, I tested it when you released the fix and again yesterday. Works great. thanks!
