### ISSUE TITLE
Doesn't use default password type setting

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#23]
The extension doesn't use what the setting page has stored for the default password type. I set it to maximum, but it consistently gives me long password types for new sites.

2.0.1pre2

**Comment by ttyridal** [comment]
You are quite right.. This seems to be something new with 2.0.1pre2. in 2.0.0 it appears to work properly.

**Comment by ttyridal** [comment]
Interestingly this bug disappears when I enabled "always use private browsing"
