### ISSUE TITLE
Importing without creating new user

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#26]
In order to maintain an accurate site list between the official iOS app and this extension I am trying to use import/export, but the problem is I cannot import a mpsites file into the extension without first creating the user, which in turn when imported into iOS creates a new user (iOS app lets the user create multiple profiles) rather than update the existing user. Now I am only assuming here, but the issue seems to be on the extension, for not allowing the user to import an existing mpsites to the fullest extent. But if this is deemed to be an iOS bug we can bring Maarten into this issue either here on his issue tracker.

**Comment by ttyridal** [comment]
I finally got hold of an Ipad to test. I can't reproduce your report. (ios app version Master Password 2.1.88, build 2188063092190)
1. Create user on iOS. 
2. add some sites. 
3. export to email
4. create user with same name and password (possible new feature, read from mpsites file)
5. import mpsites.
6. (do some edits, like add a site)
7. export and send back on email
8. open on iPad. iOS app asks for password and importing overwriting n, new m

**Comment by ghost** [comment]
I am now assuming it to be an iOS app bug (@lhunath ; reporting to youtrack now). The issue ONLY seems to happen when the iOS app is NOT running in the background (closing the iOS app by double tapping the home button and swiping the iOS app upward makes it close). If the app is already open it imports to the existing user.

**Comment by ghost** [comment]
On a side note, do you know where/how firefox stores the site data on the hard drive?

**Comment by ttyridal** [comment]
Yes,
`<profiledir>/jetpack/jid1-pn4AFskf9WBAdA\@jetpack/simple-storage/`
where profiledir is, depends on your system (windows/linux/mac). It should be ~/.mozilla/ on linux.
