### ISSUE TITLE
Support KDE5/KF5 wallet integration

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#31]
opensuse 42.2
firefox 50.1.0
masterpassword 2.0.2

"kdewallet" wallet is already created and opened

then
i install masterpassword addon
then
i choose to store the key password to kwallet
then
i restart FF
then
the procedure to create a wallet is launched and asks for me to choose the method of crypting, etc.

if i cancel this then at next launch of FF there is the same problem.

if i accept to follow the procedure to create a wallet then
each time i launch FF masterpassword asks for me the kdewallet password to open it!

**Comment by promeneur** [comment]
also if i fill the password of the kdewallet then masterpassword does not record the key  password.

i created myself the record (masterpassword-for-firefox-master, <key>) in the wallet
then
now at least i have just to supply the password of the wallet which is already opened!

**Comment by ttyridal** [comment]
Hi,

Has it always done this, or had you upgraded os or browser just before?

**Comment by promeneur** [comment]
opensuse 13.1 no problem
opensuse 42.2 problem

i have just made a clean install of opensuse 42.2

another phenomenon:
i launch FF
i fill the wallet password then i click on "..." then i see that masterpassword is not opened
then
i  quit then relaunch FF
then
this time
masterpassword is opened

**Comment by promeneur** [comment]
another phenomenon:

masterpassword-for-firefox does not ask authorization for using the wallet
and is not in the list of connected apps in kwallet manager

**Comment by promeneur** [comment]
there is something new with opensuse 42.2:
single signon technology
signon-kwallet-extension
pam-kwallet

i use pam-kwallet to open kdewallet by opening a kde session

**Comment by ttyridal** [comment]
Sounds like they've changed something in the kwallet api that breaks integration.

Unfortunately [Mozilla has decided to deprecate](http://arstechnica.com/information-technology/2015/08/mozilla-sets-plan-to-dump-firefox-add-ons-move-to-chrome-like-extensions/) the required interfaces, so kwallet (and also gnome/windows/osx variants) will soon stop working anyhow. 

Because of this development, I think it is better to investigate if it's possible to solve os-password-store integration under this new addon-api. If anyone else is interested in tracking down what's changed in opensuse 42 and implement it. I'd be happy to included it.

**Comment by promeneur** [comment]
i found where is a part of the problem.

location of the wallet files kwallet.kwl and kwallet.salt changed

with opensuse 13.1 thus kwallet 4.x these files are at /home/<user>/.kde4/share/apps/kwallet/

with opensuse 42.2 thus kwallet 5.x these files are at /home/<user>/.local/share/kwalletd/

**Comment by ttyridal** [comment]
Possible, but unlikely. MP is accessing kwallet through dbus. Turning on debug logging might provide some clues.

Another thing you can try is to switch to "secret services" as the key storage provider. It is possible that kde now implements this api.

**Comment by promeneur** [comment]
> Another thing you can try is to switch to "secret services" as the key storage provider. It is possible that > kde now implements this api

i checked this. this does not work.

**Comment by ttyridal** [comment]
I've finally had a look at this. Partially I would blame kde :( They have two interfaces to kwallet: one version specific and one generic (one would think). The addon uses the later. Even so, this will not address your default kwallet5, but rather kwallet4! 
This is why you're requested to create a new wallet: _they are completely separate_.
(and regarding file locations, you'll find that, after creating a wallet through MasterPassword, there will be one at the old location). 
`zypper install kwalletmanager` will give you the kde4 manager so you can inspect the wallet used by masterpassword (the new one is named kwalletmanager5)

The rest of your system, pam etc will use (and open at login) the kwallet5, but the kwallet4 is only first touched when you open Firefox the first time, and so you're asked to unlock it. Apparently KDE folks foresee both running at the same system, so you might find a way for pam to unlock both.

This means we're out of luck. I can change it to try the kwallet5 api first, but it's back to square one the next time they change it. Though, I'll do this going forward with the rewritten MP. 

background info:
https://barlog.rusu.info/valentin/blog/?p=395

**Comment by ttyridal** [comment]
The 2.1 beta is now released and will handle Kwallet in kde5
