### ISSUE TITLE
Is the fixed keyboard shortcut causing you trouble

### ISSUE THREAD

**Issue by ttyridal** [ttyridal/masterpassword-firefox#32]
In version 2.1 and later, it is no longer possible to customize the keyboard shortcut.  This is due to the new webextensions api from Mozilla and can't be "fixed" in this addon

If this is causing too much trouble (like, conflict with other addons) please react to this issue. With enough reports I'll disable the shortcut.

**Comment by promeneur** [comment]
Opensuse 42.2
KDE 16.08
FF 52.0
masterpassword 2.1b5

no problem with alt_shift_p and other addons.

**Comment by bradmont** [comment]
Has this been disabled? The addon recently updated for me, and the shortcut no longer works. I used it constantly, it's much easier than clicking the icon.

**Comment by ttyridal** [comment]
@bradmont No it's still in there: alt-shift-P, or on mac: ctrl-shift-P

**Comment by bradmont** [comment]
Oh, that's strange. I had it mapped to ctrl+alt+p before, but alt+shift+P doesn't seem to be working either.

Firefox 52.0.2 (64-bit)
Linux (ElementaryOS Freya)
MasterPassword 2.2.0

**Comment by ttyridal** [comment]
@bradmont 

Yes, that's one of the unfortunate consequences of the new Firefox. the hot key combo is configured at build time and not user configurable (as far as I've found)

If you enter "about:debugging" in the navigation bar, and start debugging MP. Do you get anything when pressing alt-shift-p?

**Comment by bradmont** [comment]
@ttyridal 

Sorry for taking a while to get back to you, I was travelling and didn't have much time. I haven't used the add-on debugging interface before, so I may be missing something, but I get nothing at all on the console (other than "background.js loaded"). Is it possible the hotkey is assigned differently on Linux?

**Comment by ttyridal** [comment]
@bradmont Looks like like it's not reacting at all. I'm testing this on Linux myself (firefox v54). Typically you should (when pressing the hotkey combo) see the same sequence as when clicking the icon (typically: "pre-main prep time", "calc password" etc)

Unfortunately I've still not found any way to observe existing shortcuts nor modify them. Do you have other plugins installed?

**Comment by bradmont** [comment]
I'm not sure what has changed, but the shortcut is working fine now. :)

**Comment by ttyridal** [comment]
turns out it's not fixed.. just very well hidden.

for firefox:
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

for chrome:
chrome://extensions/shortcuts
