### ISSUE TITLE
2.1b2,system password vault failed

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#33]
opensuse 42.2 with kde

i updated to masterpassword 2.1b2
then
in konsole
********************************************************************************************************************************
x@linux-eauv:~/Téléchargements> sudo python pwvault_gateway_dbus.py install --global kwallet firefox
Installed /usr/local/bin/pwvault_gateway_kde
Created /usr/lib/mozilla/native-messaging-hosts/no.ttyridal.pwvault_gateway.json
x@linux-eauv:~/Téléchargements>
********************************************************************************************************************************
then
i relauch FF
then
i click the masterpassword icon
then
i see in red "system password vault"

here is the error log
********************************************************************************************************************************
Could not read chrome manifest 'file:///usr/lib64/firefox/chrome.manifest'.
Warning: attempting to write 11018 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: NetUtil.newChannel(uri) deprecated, please provide argument 'aWhatToLoad'
Warning: attempting to write 11018 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Avertissement : « nsIOService::NewChannel() » est obsolète, veuillez utiliser « nsIOService::NewChannel2() »  HTTPSRules.js:253:18
SSL Observatory WARN: Failed to initialize NSS component:Error: couldn't open library /usr/lib64/firefox/libnss3.so: /usr/lib64/firefox/libnss3.so: Ne peut ouvrir le fichier d'objet partagÃ©: Aucun fichier ou dossier de ce type
L’utilisation de « nsIDOMWindowInternal » est obsolète. Veuillez utiliser « nsIDOMWindow » à la place.  bootstrap.js:43:20
1487153522102	addons.webextension.lemonde-decodex@lemonde.fr	WARN	Loading extension 'lemonde-decodex@lemonde.fr': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1487153522216	addons.webextension.lemonde-decodex@lemonde.fr	WARN	Please specify whether you want browser_style or not in your browser_action options.
1487153522466	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing permissions.9: Unknown permission "privacy"
1487153522475	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1487153522476	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
1487153522520	addons.webextension.languagetool-webextension@languagetool.org	WARN	Loading extension 'languagetool-webextension@languagetool.org': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1487153522521	addons.webextension.languagetool-webextension@languagetool.org	WARN	Loading extension 'languagetool-webextension@languagetool.org': Reading manifest: Error processing offline_enabled: An unexpected property was found in the WebExtension manifest.
1487153522687	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Please specify whether you want browser_style or not in your browser_action options.
L’utilisation d’XMLHttpRequest de façon synchrone sur le fil d’exécution principal est obsolète à cause de son impact négatif sur la navigation de l’utilisateur final. Consulter http://xhr.spec.whatwg.org/ pour plus d’informations.  socialwidgetloader.js:80:2
Erreur d’analyse XML : mal formé
Emplacement : jar:file:///home/roubach/.mozilla/firefox/sijiog9c.default/extensions/jid1-MnnxcxisBPnSXQ@jetpack.xpi!/data/socialwidgets.json
Numéro de ligne 1, Colonne 1 :  socialwidgets.json:1:1
Loading badgers into the pen.  background.js:781:1
In add-on jid1-MnnxcxisBPnSXQ@jetpack, attempting to use listener "tabs.onReplaced", which is unimplemented.  ExtensionUtils.jsm:1611:64
Privacy badger is ready to rock!  background.js:792:1
Set DEBUG=1 to view console messages.  background.js:793:1
tab is undefined  background.js:169
TypeError: document.querySelector(...) is null[En savoir plus]  install.js:76:24
1487153536884	addons.webextension.jid1-pn4AFskf9WBAdA@jetpack	WARN	Loading extension 'jid1-pn4AFskf9WBAdA@jetpack': Reading manifest: Error processing incognito: Invalid enumeration value "split"
1487153536897	addons.webextension.jid1-pn4AFskf9WBAdA@jetpack	WARN	Loading extension 'jid1-pn4AFskf9WBAdA@jetpack': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1487153536984	addons.webextension.jid1-pn4AFskf9WBAdA@jetpack	WARN	Loading extension 'jid1-pn4AFskf9WBAdA@jetpack': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
background.js loaded  background.js:199:1
Security wrapper denied access to property (void 0) on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported.  (source inconnue)
pwvault_gw: pwget  background.js:26:5
No such native application no.ttyridal.pwvault_gateway  NativeMessaging.jsm:188
pwvault_gateway failed disconnect  background.js:168:21
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="r" modifiers="accel,alt" id="toggleReaderMode"  browser.xul
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="i" modifiers="accel,alt,shift" id="key_browserToolbox"  browser.xul
TypeError: this._recipeManager is null[En savoir plus]  LoginManagerParent.jsm:75:9
store masterkey  background.js:96:17
pwvault_gw: pwset  background.js:26:5
chrome storage Array [ "username", "key_id" ]  background.js:109:5
Invalid chrome URI: /
No such native application no.ttyridal.pwvault_gateway  NativeMessaging.jsm:188
disconnect  background.js:100:39
Successfully compiled asm.js code (total compilation time 151ms; caching disabled in FF51 due to bug; will be reenabled in FF52)  scrypt-asm.js
pre-main prep time: 3 ms  scrypt-asm.js:1:777
pwvault_gw: pwget  background.js:26:5
No such native application no.ttyridal.pwvault_gateway  NativeMessaging.jsm:188
pwvault_gateway failed disconnect  background.js:168:21
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  github-a1397670a55955ea22f52704b06d1d917c9b5a48936cab321f8a2dcf17f9b1de.js:6:14304
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
La ressource à l’adresse « https://www.google-analytics.com/r/collect » a été bloquée car la protection contre le pistage est activée.[En savoir plus]  Key-vault-troubleshooting
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
pre-main prep time: 2 ms  scrypt-asm.js:1:777
Successfully compiled asm.js code (total compilation time 112ms; caching disabled in FF51 due to bug; will be reenabled in FF52)  scrypt-asm.js
pwvault_gw: pwget  background.js:26:5
pwvault_gateway failed disconnect  background.js:168:21
No such native application no.ttyridal.pwvault_gateway  NativeMessaging.jsm:188
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  github-a1397670a55955ea22f52704b06d1d917c9b5a48936cab321f8a2dcf17f9b1de.js:6:14304
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
La ressource à l’adresse « https://www.google-analytics.com/collect » a été bloquée car la protection contre le pistage est activée.[En savoir plus]  masterpassword-firefox
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
La ressource à l’adresse « https://www.google-analytics.com/collect » a été bloquée car la protection contre le pistage est activée.[En savoir plus]  31
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Invalid chrome URI: /
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  github-a1397670a55955ea22f52704b06d1d917c9b5a48936cab321f8a2dcf17f9b1de.js:6:14304
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
La ressource à l’adresse « https://www.google-analytics.com/collect » a été bloquée car la protection contre le pistage est activée.[En savoir plus]  31
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  github-a1397670a55955ea22f52704b06d1d917c9b5a48936cab321f8a2dcf17f9b1de.js:6:14304
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
La ressource à l’adresse « https://www.google-analytics.com/collect » a été bloquée car la protection contre le pistage est activée.[En savoir plus]  27
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
pre-main prep time: 2 ms  scrypt-asm.js:1:777
Successfully compiled asm.js code (total compilation time 166ms; caching disabled in FF51 due to bug; will be reenabled in FF52)  scrypt-asm.js
pwvault_gw: pwget  background.js:26:5
pwvault_gateway failed disconnect  background.js:168:21
No such native application no.ttyridal.pwvault_gateway  NativeMessaging.jsm:188
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  github-a1397670a55955ea22f52704b06d1d917c9b5a48936cab321f8a2dcf17f9b1de.js:6:14304
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
Firefox ne peut établir de connexion avec le serveur à l’adresse wss://live.github.com/_sockets/VjI6MTU0MDc5NzI1OmRlOWJhMjAzMjI5ZTg3ZWNiMzZmOTRiMjE3NTc2MjQ3MjI2OWZjODAzMTQwNTlkMjhjOGYxOTljNzEwYTA5OTU=--8a22a4627cb33cbe4338a4450564dd98422e441a.  github-a1397670a55955ea22f52704b06d1d917c9b5a48936cab321f8a2dcf17f9b1de.js:5:16941
La ressource à l’adresse « https://www.google-analytics.com/r/collect » a été bloquée car la protection contre le pistage est activée.[En savoir plus]  wiki
La connexion avec wss://live.github.com/_sockets/VjI6MTU0MDc5NzI1OmRlOWJhMjAzMjI5ZTg3ZWNiMzZmOTRiMjE3NTc2MjQ3MjI2OWZjODAzMTQwNTlkMjhjOGYxOTljNzEwYTA5OTU=--8a22a4627cb33cbe4338a4450564dd98422e441a a été interrompue pendant le chargement de la page.  github-a1397670a55955ea22f52704b06d1d917c9b5a48936cab321f8a2dcf17f9b1de.js:5:16941
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
Une chaîne vide a été transmise à « getElementById() ».  github-a1397670a55955ea22f52704b06d1d917c9b5a48936cab321f8a2dcf17f9b1de.js:6:14304
Une chaîne vide a été transmise à « getElementById() ».  frameworks-b0d504a21e5761da5ec5eade7ed594f51a8583550c5666e515607039056c976d.js:6:7699
La ressource à l’adresse « https://www.google-analytics.com/collect » a été bloquée car la protection contre le pistage est activée.[En savoir plus]  NativeBridge-Linux
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:657:6
********************************************************************************************************************************

**Comment by promeneur** [comment]
i found where the problem is.

native-messaging-hosts and kmozillahelper must be copied in /usr/lib64/mozilla/ and not in 
/usr/lib/mozilla/

**Comment by promeneur** [comment]
with this fix no more problem
and masterpassword key is well recorded in kwallet5

**Comment by ttyridal** [comment]
Hi, I'm not sure I understand. 
Did you copy some firefox files around ? (looks like firefox is looking for it's files at the wrong places from the log at least).

the native-messaging-hosts should perhaps be created in both /usr/lib and /usr/lib64. ([mozilla spec](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#Linux) says *any of* though)

Glad you have it working!

**Comment by promeneur** [comment]
>> Hi, I'm not sure I understand.
>> Did you copy some firefox files around ?
i move native-messaging-hosts and kmozillahelper to /usr/lib64/mozilla
then
i deleted /usr/lib/mozilla/

**Comment by promeneur** [comment]
badly fixed
kmozillahelper is not copied in /usr/lib64/mozilla/

**Comment by ttyridal** [comment]
Yeah, I know, that's a file from the firefox installation, so not inclined to move it.

Are you sure you where required to move that one? My 64-bit suse vm worked just fine without moving it.

**Comment by promeneur** [comment]
i checked there is no problem without it
