### ISSUE TITLE
wiki,bad command to install the helper

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#34]
the good command for kde and FF is
sudo python pwvault_gateway_dbus.py install --global kwallet firefox
and not
sudo python pwvault_gateway_dbus.py install --global firefox kde

**Comment by ttyridal** [comment]
You are absolutely right. Thanks

**Comment by promeneur** [comment]
badly fixed
you wrote
python pwvault_gateway_dbus.py install --global firefox kwallet
instead of
sudo python pwvault_gateway_dbus.py install --global kwallet firefox

**Comment by ttyridal** [comment]
you mean missing the sudo?

**Comment by promeneur** [comment]
if you use --global you need to get admin rights
and
you wrote firefox kwallet instead of kwallet firefox

**Comment by ttyridal** [comment]
Ok, thanks.. 

The order of operators actually doesn't matter, but it's nice that they match potential output from the pwvault_gateway.
