### ISSUE TITLE
Bug: MP does not recognize / populate password field consistently

### ISSUE THREAD

**Issue by jamesdwilson** [ttyridal/masterpassword-firefox#39]
MP ver:
2.10b4

ff ver:
51.0.1

os ver:

linux mint 18
Linux thinkpad 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

0. have mp set to autopopulate password field and to submit form
1. load page
2. click password field
3. click mp firefox addon
4. mp tries to populate and submit form
5. mp fails to populate field, and does try to submit form. 

expected:

1. mp should populate password field
2. should submit form

actual:

1. mp does not populate password field
2. mp attempts to submit form, but fails due to missing password

notes:

if i select the password field and hit the icon again, after once or twice again it eventually works.

**Comment by ttyridal** [comment]
Hi, 

is this on some particular site or all of them? 
was it working better with the previous version?  (the password inject was "improved" in beta4)

**Comment by jamesdwilson** [comment]
Try with creditkarma.com

**Comment by jamesdwilson** [comment]
Also mint/intuit

**Comment by ttyridal** [comment]
Thanks.. I can reproduce it. will look into it asap. I'm guessing it's a timing issue. The inject script runs on document_end, so one hypothesis is that your too fast / the site is too slow..  Not sure if that's actually required.

**Comment by ttyridal** [comment]
Are you sure it actually tries to submit the form ?

When I'm trying to reproduce the error I get a "No password field found" error in the browser log (Ctrl-Shift-J). Log window need to be open before clicking MP button.

It appears to be a timer that is a bit too tight.

**Comment by ttyridal** [comment]
hopefully fixed in beta 5
