### ISSUE TITLE
Is 2.1 submitted for review?

### ISSUE THREAD

**Issue by jedahan** [ttyridal/masterpassword-firefox#43]
Looking at https://addons.mozilla.org/en-US/firefox/addon/masterpassword-firefox , is there a way I can manually install 2.1 now?

**Comment by ttyridal** [comment]
Yes it's submitted, and no, as far as I know, there is no way to get the signed file up front.

I can publish the unsigned version, but that won't help you much if your not on nightly or developer versions of Firefox.

**Comment by jedahan** [comment]
Cool, thanks for the info

**Comment by ttyridal** [comment]
btw: if you're not following the development channel, you can get everything but a few last minute bug fixes by doing that.  all the way at the bottom of the page you linked.
