### ISSUE TITLE
2 ways sync mpsites between and roid and linux

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#46]
Hello

i want to sync (2 ways) mpsites between android and linux.

i want to use android+unison and linux+unison and google drive.

but
where is the mpsites file in linux in .mozilla?
where is the mpsites file in android?

thanks

**Comment by ttyridal** [comment]
I don't know anything about masterpassword for android I'm afraid. Masterpassword for Firefox does not store an mpsites anywhere. Mpsites is the file format of masterpasswordapp. mp-ff can export and import .mpsites, but it is too limited for mp-ff. F.ex it's not possible to store the url the settings are associated with.

mp-ff store its data in a json file somewhere under your profile
