### ISSUE TITLE
key id mismatch 

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#48]
if i import .mpsites of mpw desktop
then
i get an error message
Key ID mismatch!

i compared the 2 key ids.
they are same but in your .mpsites keyid is made of a,b,c,d,..x,y,z and digits
mpw desktop key id is made of A,B,C,...,X,Y,Z and digits
android mpw key id is made of A,B,C,...,X,Y,Z and digits

**Comment by ttyridal** [comment]
Sounds like I'm missing a ignore case there.. will confirm and fix.

**Comment by ttyridal** [comment]
Version 2.3 awaiting review and release from AMO
