### ISSUE TITLE
does not fill id,pw for bugs.kde.org

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#49]
i go to bugs.kde.org
then
i click on login
then
i click on mpw icon
then
id and pw fields are not filled

**Comment by promeneur** [comment]
same problem with bugzilla.mozilla.org/

**Comment by ttyridal** [comment]
fixed in commit 7eef0c1c42d included in 2.2 release awaiting approval at mozilla.

As a future warning:
There will likely be a million sites that don't follow the best practices for login forms and hence will not be able to auto complete the username.

**Comment by promeneur** [comment]
you are right that was the case for FF mechanism for some sites among the 190 sites i use to connect.
i made reports about them to bugzilla.mozilla.org

**Comment by promeneur** [comment]
thanks for the fix

**Comment by ttyridal** [comment]
> i made reports about them to bugzilla.mozilla.org

imho, you should really direct that bug report to the site. The browser would be unacceptably slow if it was to support all the crazy ways you could make a login form. (for mp-ff it's even slower, and I'm stricter than the browsers, basically trying to prevent users from pasting username/password at the wrong place.)
