### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#5]
It would be very helpful if you would add import/export features to your addon, so that users who have created a massive list of sites in the format user@site.com, or user@email.com@site.com can easily start using your addon. This import/export feature should be compatible with the other masterpassword tools

**Comment by ttyridal** [comment]
Hi, 
In what formats would you like to see the import/export ? 

As far as I'm aware, only the ios version has an export/import feature (I don't have an I-device) in a "non standard" format. The unofficial Android app does have json, which could be quite handy.

**Comment by ghost** [comment]
I don't know the details myself, you would have to talk at Maarten for that. I'm just looking for compatibility with the other masterpassword products.  I know that the iOS and Java app uses the same format and I believe that the Mac app too.

**Comment by ttyridal** [comment]
Ah, yes, found it in the java version, and the relevant code in Maarten's repository.  I think it should be fairly easy to add.

Now how to add that in a visually pleasing way..

**Comment by ttyridal** [comment]
in master

**Comment by ghost** [comment]
Have you updated the firefox addon with the import/export functionality? I can not seem to locate it.

**Comment by ttyridal** [comment]
Hi, I just uploaded v0.99.6 to github. I've not had much chance to test the import/export feature my self, so please report if you have any issues.
