### ISSUE TITLE
Masterpassword toolbar button disappeared

### ISSUE THREAD

**Issue by danielneu** [ttyridal/masterpassword-firefox#50]
HI,

I'm using this extension since a long time. Lately, the button vanished form the toolbar and I cannot get it back.
Tried uninstall / install and to manually put it there via customization of the toolbar.

I'm running Firefox ESR 45.9.0, is there maybe an issue with ESR releases of Firefox?

Any help would be appreciated.

Best wishes 
Daniel

**Comment by ttyridal** [comment]
Hi, 

Is "lately", after updating? to v2.1.x or v2.2.0 ?
They are only supporting Firefox >= 51  You should have been prevented from doing the upgrade in that case, but it might have failed.

Try downgrading to 2.0.2:
https://addons.mozilla.org/en-US/firefox/addon/masterpassword-firefox/versions/?page=1#version-2.0.2

**Comment by danielneu** [comment]
Thanks a lot,

this solved the issue.

Best wishes 
Daniel
