### ISSUE TITLE
Upgrade masterpassword-firefox so Firefox 57 does not stop allowing it

### ISSUE THREAD

**Issue by coder543** [ttyridal/masterpassword-firefox#51]
It appears that `masterpassword-firefox` is using the legacy plug-in API, which (I think) means users will no longer be able to install or use this extension when Firefox 57 ships. It looks like Firefox 57 will ship before the end of the year. As someone who just switched from Chrome to Firefox with the release of Firefox 54, it would be nice to have this extension keep working!

![legacy](https://user-images.githubusercontent.com/726063/27158318-54aa6456-5134-11e7-80a1-89cd1f5afbdc.png)

**Comment by coder543** [comment]
Needless to say, this is probably a lot of work, but I didn't see an issue for it, so I figured I would go ahead and open one just in case it will be an issue.

**Comment by ttyridal** [comment]
Hi, 

This is taken care of. Version 2.2 (the latest stable) is a transition release to transfer user data between old and new api. In practice it is a new (webextension) addon wrapped inside the old extension api.

The next major release (probably in july/august) will be pure webextension and the transition is complete.

**Comment by coder543** [comment]
Alright, that sounds great!

**Comment by coder543** [comment]
Nightly has now disabled legacy extensions, so I can't use mpw on Nightly, which I've been running for a little while now. Just FYI.

**Comment by ttyridal** [comment]
Yes, two months fly past at terrible speed..  a pure webextension version should now be available in the beta channel !

**Comment by ttyridal** [comment]
version 2.3 awaiting review and release from AMO
