### ISSUE TITLE
www.x.y.z and www.t.y.z are falsy same site y.z for masterpassword

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#52]
i have an account at www.ter.sncf.com with id1 and pwd1.
i have an account at www.moncompte.sncf.com with id2 and pw2.
these are different accounts. i cant' unify them.

for the 2 sites for masterpassword site name is sncf.com.

for generating pwd i chose ter.sncf.com and moncompte.sncf.com then all is well recorded
but
if i go to www.ter.sncf.com or www.moncompte.sncf.com
then
i must select the good site name in the list supplied  by masterpassword to fill the pwd field with pwd.

can you automate this ?

**Comment by promeneur** [comment]
there is also an ennoying behavior of masterpassword: 
if i click on "..." the password field is filled with the pwd of the first occurrence of sncf.com stored in "stored sites"

**Comment by ttyridal** [comment]
This has been addressed in version 2.9, now released.

Please reopen if the issue still applies
