### ISSUE TITLE
mpw 2.3.0, restore site list with 2.2.0 storage.js ?

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#53]
Hello

i don't have any .mpsite file
i have only a storage.js file of a 2.2.0 installation in a backup.
how to import  this storage.js file to a 2.3.0 installation ?

thanks

**Comment by ttyridal** [comment]
Hi, there is no way to directly import the storage.js as it is stored in a Firefox implementation defined format.

Two alternatives:
1) Setup a profile with v2.2.0, place the storage.js in the appropriate folder, start Firefox and export a .mpsites 

2) If you don't have too many sites, storage.js should be human readable, import manually.


If you upgraded from a 2.2.0 installation, your sites should have converted over automatically !?

**Comment by promeneur** [comment]
thanks
success

why not adding a new feature "import settings from another FF installation"

i mean by settings:
-settings
-data

**Comment by ttyridal** [comment]
The new format (replacing .mpsites) proposed by the inventor will have the possibility to also store settings.
