### ISSUE TITLE
.mpsites import into Android FF,  How?

### ISSUE THREAD

**Issue by charliemb2** [ttyridal/masterpassword-firefox#58]
Has anyone figured out how to import an .mpsites file in Android Firefox?

I surmise that this extension was written for the desktop where drag and drop is a normal operation.  But drag and drop is not really an Android UI option for transferring a file between apps, that I know of.

**Comment by ttyridal** [comment]
Hi,

I have no idea if that's possible or not. Unfortunately I don't have the time nor interest to make sure the plugin works on android - But I will happily apply patches :)

**Comment by ttyridal** [comment]
Version 2.9, just released has an import **button** in addition to the drag-n-drop feature. Hopefully that would solve it

Please reopen if still an issue
