### ISSUE TITLE
using same storage for android masterpassword and android FF masterpassword 

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#61]
Hello happy new year

It would be a good thing to use same storage and not only same storage format between android masterpassword and android FF masterpasssword.

See https://github.com/dkunzler/masterpassword

Also, why not merge the two apps in one app ?

Also, this one app could be an automatic filling service for android like lockwise.

Thanks

**Comment by ttyridal** [comment]
Would have been nice, but I can't see how it should be done. This project is a browser plugin that should work on all platforms (actually, I'm only targeting desktop - that it works in mobile browser is "by accident"), while the other is an android app.

**Comment by promeneur** [comment]
Hello

i did not well explain:

the idea is to store masterpassword "id and pwd" data in FF password storage.

In the past there were a plugin to store FF id and pwd in kwallet.
FF "id and pwd" storage management must be disabled.
each time if for the first time you fill an id and pwd plugin asks you to store an id and pwd then this "id and pwd" is duplicated in kwallet and FF password storage.

If you investigate what is stored in Firefox pwd storage you see :

- simple chains of symbols where you can find URL, id, pwd etc.
- chain where "password" value is something like that
{"version":1,"accountData":{"kA":"65daad5841...30888909","kB":"016d30617fbd...1c5660f76"}}

i assume you can store masterpasword data in "password"

also each record gets a name like this for example

0ee4b0d1...7bdd70,,Firefox Accounts credentials,chrome://FirefoxAccounts

you can also store some data in the record name
