### ISSUE TITLE
pwvault_gateway_dbus.py fails with 'Failed: can't concat str to bytes'

### ISSUE THREAD

**Issue by RubenKelevra** [ttyridal/masterpassword-firefox#62]
I tried to install the helper for kwallet / chrome and the script just fails with:

> Failed: can't concat str to bytes

**Comment by ttyridal** [comment]
Hi, thanks for reporting this. 

What was the command you issued?

Sounds like a python3 issue. The script should work in both python3 and python2, but you might have greater success forcing it to use python2

**Comment by RubenKelevra** [comment]
I've followed the 'help' link in the Chrome extension, this opens the [page](https://github.com/ttyridal/masterpassword-firefox/wiki/Key-vault-troubleshooting). I've selected `NativeBridge Linux` and downloaded the [linked](https://raw.githubusercontent.com/ttyridal/masterpassword-firefox/master/native_bridge/linux_dbus/pwvault_gateway_dbus.py) python script.

The command was `$ python pwvault_gateway_dbus.py install kwallet chrome`.
```
$ python --version
Python 3.8.1
```

> Sounds like a python3 issue. The script should work in both python3 and python2, but you might have greater success forcing it to use python2

Python 2 is EOL, so it's not installed on my system.

**Comment by RubenKelevra** [comment]
I've updated to Python 3.8.2 and fetched the latest version, but it's still broken :/

**Comment by mil2house** [comment]
Hi.

I`m report the same fail on Kwallet (KDE5) and Firefox. Python 3.8.5
Failed: can't concat str to bytes

Please, is possible repare it? Thx. :)

**Comment by ttyridal** [comment]
So, finally had the time to look quickly into this.  Have you tried it afterwards? The error reported on install is actually the very last line, just stating "install successful" - so it *should* work regardless. 

might be other similar issues though

**Comment by ttyridal** [comment]
you can test without firefox by the way:

`pwvault_gateway_dbus.py test kwallet pwget` and `pwvault_gateway_dbus.py test kwallet pwset sssh-secret-password`

(a bit embarrassed to admit I don't have a linux desktop at the moment 🙄)

**Comment by ttyridal** [comment]
tested with kubuntu 20.04 working ok. needs python-is-python3 package
