### ISSUE TITLE
Does not work in private window

### ISSUE THREAD

**Issue by bradmont** [ttyridal/masterpassword-firefox#63]
When I try to use masterpassword in a Firefox private window, it does not load; the window appears, with "loading..." in the grey status bar at the bottom, but it goes no further. I cannot specify an identity or a master password; I need to open a new tab in a non-private window, type in the site name, and then copy and paste the password, which is kind of annoying.

thanks!

**Comment by ttyridal** [comment]
Thanks..  

seems like https://bugzilla.mozilla.org/show_bug.cgi?id=1329304 is the problem and the solution is to use `browser.runtime.sendMessage` instead..  Looking through the history I vaguely remember this was how it worked with the old extension api..

**Comment by ttyridal** [comment]
released in 2.3.1 beta1

**Comment by bradmont** [comment]
Great, thank you! Though it looks like the link to the latest beta build is broken.

**Comment by bradmont** [comment]
Oh, the extension just auto-updated for me and it's working fine! Thanks!
