### ISSUE TITLE
[news] Masterpassword deprecated in favor of spectre

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#66]
Hello

Yesterday I discovered that masterpassword is deprecated in favor of Spectre, but Spectre as a new solution is not ready. See spectre.app site.

There is no more update of the different versions of masterpassord.

It seems there is a new api.

Today there is only a package for IOS. See https://chat.spectre.app/d/80-wip-for-linux-desktop-android/2
There is no  
-  gui.jar and cli for Linux desktop
-  .apk for android
-   no plugin for Firefox and Chrome

**Comment by ttyridal** [comment]
Hi
Thanks for the heads up! 

Yes I've seen it. At the moment it seems like it's just a rename for 'branding' and trying to chase a 'freemium' model. The file format looks to be the same still (and still called 'mpsites') and the algorithm is the same. 

Basically it depends a bit on where Maarten wants to take it. He could let Spectre be "just another implementation" or he could take it in some other direction.
I guess we would just have to wait and see.

Meanwhile, the browser extension, the various app implementations etc remains compatible for the time being.

**Comment by ttyridal** [comment]
Oh, and "Deprecated" is a strong word here.  The algorithm remains open and free and there is a large ecosystem of implementations now. It's only the original implementation that is changing name.
