### ISSUE TITLE
Instructions for developoing with chrome/webkit browsers

### ISSUE THREAD

**Issue by jmorgannz** [ttyridal/masterpassword-firefox#67]
Hi,
I plan to make some pull requests for new features; what is the state of Chrome / WebKit / Bliink browsers with this plugin now?  
Does it work?  How do I set it up so I can test my work?

**Comment by ttyridal** [comment]
Hi. 

The future branch is regularly tested against both Firefox and Chrome and should work 100% on both browsers. I haven't yet come around to test with others (ie chromium, edge, Safari(?) or Vivaldi)

To test, just load a 'unpacked' extension from the ext/webextension folder

On My setup (on Linux/osx) I have a symlink to src in the chromeext folder (so Chrome can load form its own manifest).  An alternative is to copy the chrome manifest into the webextension folder..  

They need (I think) separate manifest files to maintain the Id from the stores.
