### ISSUE TITLE
Import non functional

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#7]
Import does not function when dropping a .mpsites file exported from the official iOS app, or the java app. I'm not sure of any errors that may have been produced, but can provide you with logs/errors if the extension produces output somewhere. Not sure if @lhunath could provide any insight as to why it doesn't work or not.

**Comment by ttyridal** [comment]
Sorry about that.. I've been bitten by developing on multiple machines..

**Comment by ttyridal** [comment]
Hi linwiz, did the latest update resolve your issues?

**Comment by ghost** [comment]
Yes, this has been resolved for me.
