### ISSUE TITLE
Browser Popup Sitename: Doesn't save changes on blur()

### ISSUE THREAD

**Issue by jmorgannz** [ttyridal/masterpassword-firefox#70]
On the popup frame if you try to alter the detected site name, it will only save the value if you use TAB or ENTER.  
If you select a different element with the mouse, the value is not saved. Instead it resets to the previous value.

**Comment by ttyridal** [comment]
nice work on organizing this stuff! Thanks!

forgot the mention in the commit, but this one is already addressed in commit baf5110
