### ISSUE TITLE
Allow editing of site name in the configuration screen

### ISSUE THREAD

**Issue by jmorgannz** [ttyridal/masterpassword-firefox#71]
Currently the sitename in the configuration screen(s) is read only.  
Would it be possible to make this editable just as the (matching) field is?

**Comment by ttyridal** [comment]
It's absolutely possible. Though, after thinking on this for a little while..  When would you actually do it? I mean, if the site name is on the list, one would assume the password has been used/set. Changing anything other than what urls to match (or login name) would change the password.
One reason for wanting to edit the site name is if the user at one point mistyped it in the popup window. presumably they corrected the error (and successfully logged in, and thus also saved the correct one), so the only reasonable action is to delete the wrong value?

**Comment by jmorgannz** [comment]
Yes this is where issues came from.
The previous situation where the sitename was reverting to default after
having manually corrected it in the popup unless your hit enter or tab lead
to an unwanted sitename being saved it stored sites.

At the time it appeared as if there was no way to get the popup to accept my corrected sitename.  

Now that I know you must press enter or tab, the issue is redundant.
(can't remember if you added on blur?)

However having had the question raised, you are asking why should the
sitename be editable.

I guess coming at it from first principals it's more pertinent to me to ask
why it shouldn't be when the other fields are.

I'm guessing it's rooted in a historical reason and other than that no
reason other than it takes dev time to change without really adding
anything.

Which is a fine reason by the way :)

**Comment by jmorgannz** [comment]
Which is a fine reason by the way :)

**Comment by ttyridal** [comment]
2 years later I'm deciding to not implement this :)

I think it will create more confusion than help, as the password generated will suddenly be different. 
The "correct" way is to create a new password the usual way and delete the erroneous entry.

(and yes,  save-on-blur was added: #70)
