### ISSUE TITLE
2.9.0b1 enables the OS password store option, which can break it when necessary support is not installed

### ISSUE THREAD

**Issue by Pointedstick** [ttyridal/masterpassword-firefox#73]
After the extension was upgraded today, it no longer seems to work. Clicking on its toolbar button produces the following:

![Screenshot_20211205_163716](https://user-images.githubusercontent.com/1097249/144768631-fb24e6e1-a5a5-4098-9ae6-f3065ad9177b.png)

Unfortunately no name or path to a log file is provided, so the message isn't particularly actionable (room for improvement).

I am using Firefox 94.0 on Fedora Linux with KDE Plasma.

**Comment by Pointedstick** [comment]
Found the issue: "Use OS's password store" got enabled on upgrade, and I didn't have the right packages installed to make this work. I don't think this should be enabled on upgrade.

**Comment by ttyridal** [comment]
Hi, that's disturbing news 😬
And thank you for reporting it!

It should also not trigger a *bug*, only a notice that it failed and give your the alternative to log in manually .

Does it work like expected if you disable the os password store option? (You can reach this from the Firefox add-on settings)

**Comment by ttyridal** [comment]
How it got enabled in the first place is a mystery though.

Anyway, thank you for reporting. Will release a fixed version shortly

**Comment by othiman** [comment]
The same happenend for me on Firefox 94.0.2 on MacOS. After upgrading to version 2.9.0b1 I also only got "BUG. please check log and report". After disabling "Use OS' password store" it works like before.

**Comment by ttyridal** [comment]
Fixed in now released v2.9.0-beta2

**Comment by Pointedstick** [comment]
Much better, thank you so much!
