### ISSUE TITLE
Clicking red-highlighted "Upgrade datastor" fails to allow imports

### ISSUE THREAD

**Issue by charliemb2** [ttyridal/masterpassword-firefox#74]
With this new version, 2.9.0b2, I am unable to import an updated .mpsites file by either dragging or clicking on the new Import button.

Clicking on "Upgrade datastor" appears to work, in that it asks questions about inconsistencies.  The "Upgrade datastor" process asks once to select between one or the other of A or B for a given site.  I clicked to kept A.  The process completes without errors flagged.   However, when I click import, or attempt to drag an mpsites file, I get an error at the top right which reads, "need data upgrade before import."

Update: In attempting to increase the counter for a particular site, I get a red banner at the bottom indicating that the save failed and that I needed to upgrade my datastor.  So it appears definite, the datastor upgrade failed to complete with no warning of such failure.  The counter did increase, allowing me to enter the site.  However, I will have to remember to increase the counter every time I go to this specific site.

**Comment by ttyridal** [comment]
Hi thanks for reporting

Have you tried to completely close (all windows) and reopen Firefox? (close and reopen the popup should actually be enough, I think)

Sounds like the "upgrade needed" flag isn't cleared for some reason/case perhaps. I will have a closer look.

**Comment by ttyridal** [comment]
@charliemb2 

did the upgrade somehow fail?  Did you get the upgrade complete message? (should pop up in top-right corner) Does the upgrade button disappear? Reappear when you reload the config page?

If you do not get the upgrade complete message, could you open the log from the config page (menu: tools, developer tools and the console window) and see if you get any hints there?  It does sound like the upgrade fails silently. It is an all-or-nothing thing. If it fails, the upgraded data is not saved.

**Comment by ttyridal** [comment]
Found an embarrassing fault there. beta 3 is now released and should correct the issue.

**Comment by charliemb2** [comment]
> Hi thanks for reporting
> 
> Have you tried to completely close (all windows) and reopen Firefox? (close and reopen the popup should actually be enough, I think)
> 
> Sounds like the "upgrade needed" flag isn't cleared for some reason/case perhaps. I will have a closer look.

For reference, I closing and opening the pop-up had no affect.  

I then uninstalled and reinstalled the add-on.  At first, this didn't work either.  But then an odd thing happened after I reinstalled it.  It disappeared.  Then, I went to go install it again and before I could finish I noticed that the icon was back.   When I clicked on it everything was blank and I could start over again.   At that point, the upgrade button wasn't present.  I was then able to import my updated .mpsites file and now everything worked.   This was all with b2.

**Comment by charliemb2** [comment]
> @charliemb2
> 
> did the upgrade somehow fail? 

Definitely it failed.  (I'm speaking in the past, when I was having the error.)

>Did you get the upgrade complete message? (should pop up in top-right corner) 

No.  Definitely not.

>Does the upgrade button disappear? 

I assume you are referring to the red-highlighted button on the gear-icon page.  No, It never disappeared.

Reappear when you reload the config page?

I never noticed that it disappeared, so no, I didn't ever notice it reappearing.

> 
> If you do not get the upgrade complete message, could you open the log from the config page (menu: tools, developer tools and the console window) and see if you get any hints there? 

Too late now.  As reported earlier,  I was able to uninstall and reinstall and eventually got to a clean state.  Now b2 works.

>It does sound like the upgrade fails silently. It is an all-or-nothing thing. If it fails, the upgraded data is not saved.

For sure it was not saved.

**Comment by charliemb2** [comment]
> Found an embarrassing fault there. beta 3 is now released and should correct the issue.

Thanks.  I'll try it.  

Edit:  Checking for updates on Firefox's about:addons page by clicking on the gear icon => "Check for updates" returns "No updates found."  
Edit2: Oddly,  I see b3 here: https://addons.mozilla.org/en-US/firefox/addon/masterpassword-firefox/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
Edit3: Oddly again, now b3 is showing at bottom of about:addons.  But I don't get the feeling like it ever updated since the only status I ever saw was "No updates found."

**Comment by ttyridal** [comment]
> I then uninstalled and reinstalled the add-on. At first, this didn't work either. But then an odd thing happened after I reinstalled it. It disappeared. Then, I went to go install it again and before I could finish I noticed that the icon was back. When I clicked on it everything was blank and I could start over again. At that point, the upgrade button wasn't present. I was then able to import my updated .mpsites file and now everything worked. 

Yes, that would do the trick.. The problem was (if the same one I fixed) related to changing the old internal format to the new.  When you start from a fresh install, it will use the new format directly.


The update works in mysterious ways. That part is on firefox / mozilla. I have no control over it :)

Hope you have a problem-free experience henceforth !

**Comment by charliemb2** [comment]
Thanks
