### ISSUE TITLE
Allow disabling of changelog popup

### ISSUE THREAD

**Issue by xeruf** [ttyridal/masterpassword-firefox#77]
I get this new tab popping up all the time, switching between machines and updating. I would really appreciate not having it in my face.

**Comment by ttyridal** [comment]
Hi, 
It's been three updates in quick succession lately,  sorry about that. 
Or, do you mean that it shows more often than this?

The stable channel should be more quiet, with less frequent updates

**Comment by xeruf** [comment]
It shows for each update on each device, and I have quite a few. I always instantly close the tab, so it is just an annoyance for me :/

I do appreciate frequent updates, but they needn't be in my face ;)

**Comment by ttyridal** [comment]
Right.. It's a balancing act. I guess one could save the note for major releases and silently upgrade on bugfix / hotfix releases.

On the other hand, if I'm bugged by an issue, I would like to know as soon as possible if it's fixed.

Can't promise anything, but keep your eyes out for a release note with notice that release notes will appear less frequent :)

**Comment by xeruf** [comment]
Or an option to disable release notes ;)

**Comment by ttyridal** [comment]
sorry, but you'll have to live with the occasional release note :). first of all because I think it's way too niche to merit an extra config option the user has to consider.
But it should be somewhat more quiet now, and not pop up on every fix released.
