### ISSUE TITLE
save failed: need data upgrade - How to upgrade

### ISSUE THREAD

**Issue by JokerGermany** [ttyridal/masterpassword-firefox#78]
From issue #74 i get that ther has to be an "Upgrade datastore"
But i didn't have one/find one.

When i open the settings i only get the message "failed loading sites" but i didn't find a button.

**Comment by ttyridal** [comment]
Hi, that doesn't sound promising.  I assume the config page is also missing all your sites? 

Could you please check the log? ctrl+shift+i, or menu-more tools-Web developer tools, then the "console" tab
This with the config page open (after the failed loading sites message)

Your browser is Firefox? 

It's the regular popup working? (Showing your saved sites?) 

I assume this is your first run with version 2.9? You have not previously upgraded the data storage?

Do you have non ASCII  (us a-z alphabet) symbols in your username, password or site names?

**Comment by JokerGermany** [comment]
> I assume the config page is also missing all your sites?

No there are 21 entries (alphabetical: number -> a -> d)
(I think he never showed me all entrys)
 
> Could you please check the log? ctrl+shift+i, or menu-more tools-Web developer tools, then the "console" tab This with the config page open (after the failed loading sites message)
```
Failed loading sites on load Error: Unknown password type:nx
    passtype_to_str moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:46
    stored_sites_table_append moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:59
    stored_sites_table_update moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:71
    <anonymous> moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:92
    async* moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:81
    <anonymous> moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:37
```

When i try to export the passwords:
```
Uncaught (in promise) unknown password type:nx sites.js:68:18
    type_as_code moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/lib/sites.js:68
    site_as_mpjson moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/lib/mpw-utils.js:71
    sites moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/lib/mpw-utils.js:182
    reduce self-hosted:261
    make_mpsites moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/lib/mpw-utils.js:182
    <anonym> moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:299
    (Async: promise callback)
    <anonym> moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:297
    (Async: EventListener.handleEvent)
    <anonym> moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:269
    <anonym> moz-extension://3ef56c9d-3a60-4330-9d71-f81a518482cc/src/options/config.js:371
    InnerModuleEvaluation self-hosted:2374
    evaluation self-hosted:2335
```

> Your browser is Firefox?

Yes

> It's the regular popup working? (Showing your saved sites?)

Yes until today everything works fine.
I assume new entrys won't work and when i try to change an entry i get the message: save failed: need data upgrade

> I assume this is your first run with version 2.9? You have not previously upgraded the data storage?

No I ignored the release notes and has done nothing until now...

> Do you have non ASCII (us a-z alphabet) symbols in your username, password or site names?

I don't know which symbols masterpassword use for the passwort.
The site names should be fine.

**Comment by ttyridal** [comment]
>I don't know which symbols masterpassword use for the passwort.

I was thinking about your master password, but never mind. It is not the issue.

>(I think he never showed me all entrys)

Oh.. Just checked with an older release, and this is a bug that's been there for >5 years 🙉. It will indeed prevent the upgrade, so more visible now. It's triggered if you have any site with password type Name [v] or Phrase [v]

Thanks for reporting!

**Comment by ttyridal** [comment]
released

**Comment by JokerGermany** [comment]
Looks like it works, thanks
