### ISSUE TITLE
Does not record any ID and pwd with Firefox private mode

### ISSUE THREAD

**Issue by promeneur** [ttyridal/masterpassword-firefox#81]
Switch to private mode with FF.
go to a site.
Fill the pwd field with masterpassword.
Log into your account.
Go to master password settings.
The ID and pwd are not recorded.

Switch to non-private mode then this time the ID and pwd are recorded.

**Comment by ttyridal** [comment]
Yes, this is intentional.
Masterpassword does not store _anything_ in private mode

**Comment by promeneur** [comment]
I don't understand ID and PWD are not cookies or data to accelerate page loading
FF records ID and PWD in private mode

**Comment by ttyridal** [comment]
You're right, it's not. It's "trace of activity" - just like entries in the browsing history (which Firefox is not making, if private browsing is active)

**Comment by promeneur** [comment]
Yes but the problem is that also in private mode we need to create account with ID and PWD

**Comment by promeneur** [comment]
I experimented this:

In private mode, Firefox supplies a password and records the id and pwd.

**Comment by promeneur** [comment]
i close this issue because this is an error
